project:
  type: website
  output-dir: docs

website:
  title: "EBINLO"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - icon: instagram
        href: https://www.instagram.com/dj.ebinlo/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

